### ISSUE TITLE
clj-http 1.0.0 dependency breaks multipart uploads in Ring with Kerodon tests

### ISSUE THREAD

**Issue by ikbrunel** [xeqi/peridot#18]
I think that I've isolated some kind of conflict between Ring and clj-http. Bringing in clj-http as a dependency only completely breaks Ring's multipart upload handling (or maybe it's Kerodon's multipart uploads...I cannot tell).

To reproduce, start by cloning:
`http://www.github.com/survantjames/crazy_clojure_deps`
Then follow the instructions in the readme.

Expected behavior:
- print statement in POST route should post the multipart params including tempfile and filename

Actual behavior:
- print statement prints empty maps 75%-90% of the time (estimated)

I'll be cross-posting this to the clj-http and Kerodon projects.

**Comment by timgilbert** [comment]
Any update on this? When I bump the httpmime dependency to 4.5, I'm seeing a different error:

```
ERROR in (uploading-a-file-with-params) (request.clj:27)
Uncaught exception, not in assertion.
expected: nil
  actual: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
 at ring.util.request$content_length.invoke (request.clj:27)
    ring.middleware.multipart_params$request_context$reify__1922.getContentLength (multipart_params.clj:29)
    org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl.<init> (FileUploadBase.java:955)
    org.apache.commons.fileupload.FileUploadBase.getItemIterator (FileUploadBase.java:310)
```

I agree with punting on the file type detection, per your last comment. As a library user, I'm happy to specify the content type in my test, even if it's somewhat redundant.

I'm definitely willing to help with testing or working on a fix for this, please let me know if there's anyhting I can do.

**Comment by glenjamin** [comment]
I'm afraid I'm not really familiar with multipart encoding - and I'm not using this particular feature, so I don't really have a horse in this race.

I'll happily accept a PR that passes tests including multipart uploads with a bumped httpmime version - it sounds like there'll have to be API changes to make this work - but that's fine.

**Comment by danielcompton** [comment]
Is this still an issue after https://github.com/xeqi/peridot/issues/44?

**Comment by danielcompton** [comment]
We're using httpmime 4.5.1 and the tests are passing. I'll close this for now, but happy to reopen if there are further issues here.
