### ISSUE TITLE
Tests with Multipart File Uploads Sporadically Fail

### ISSUE THREAD

**Issue by briankontor** [xeqi/peridot#28]
I just ran into an issue trying to write some tests around multipart file uploads on Peridot v0.4.2. Essentially, my tests would pass or fail at random. I stripped it down to even a simpler version of the multipart upload test within Peridot (https://github.com/xeqi/peridot/blob/v0.4.2/test/peridot/test/multipart.clj#L20), and can easily reproduce.

My colleague then noticed this recently merged pull request: https://github.com/xeqi/peridot/pull/27

After `lein install`ing Peridot master into my local repository, my simple test always passes. I was wondering if you were planning to push a new release of Peridot with these fixes to Clojars any time soon.  Thanks.

**Comment by glenjamin** [comment]
I'll push this out tomorrow morning

**Comment by briankontor** [comment]
Great. Thanks!

**Comment by glenjamin** [comment]
Released as `0.4.3`
