### ISSUE TITLE
Multipart uploads are broken for binary files

### ISSUE THREAD

**Issue by harold** [xeqi/peridot#44]
I believe this closed issue still exists: https://github.com/xeqi/peridot/issues/37

We found a fix today, and I added some thoughts here: https://github.com/xeqi/peridot/commit/9ac88b1abdba5b65a5a3d200f10e4a82dc37a7f8#diff-c0a4b18ad5747555d7435bbedbb27e31R45

This PR introduced the bug, I believe: https://github.com/xeqi/peridot/pull/27

Any thoughts @xeqi or @phillmv ?

Thanks again for peridot, it's a sweet lib, and if it didn't exist we'd have to create something similar. :)

**Comment by danielcompton** [comment]
Hey I'm a maintainer of this lib now, happy to look at fixing this. Can you open a PR which includes your change and also a test which demonstrates what was previously failing and now works? Looking at your code comment, is this the only line that is changing? `(clojure.java.io/input-stream (.toByteArray out))`

**Comment by harold** [comment]
Oh hi there! Good to see a familiar smiling face.

I am not having much time at the moment for open-source work, and I'd love to do what you described. We've moved forward with the proposed hack for now (the bug we were experiencing was only a bug in test). If no one else does the work and I find the time, I'll be happy to.

It is indeed just the one-line change.

hth and take care.

**Comment by danielcompton** [comment]
I've fixed this, just now, but don't have a test reproducing the original issue. If you have time to provide a PR that'd be helpful so we don't get a regression around this area.
